### ISSUE TITLE
code demande de visite

### ISSUE THREAD

**Issue by romain-malet** [romain-malet/ToulouseMusee#17]
Pourquoi ne pas juste créer un numero aléatoire unique avec un uuid au lieu de faire une requete en base de données.
Ca serait quand même bien plus light !
Je peux le faire si tu veux...

**Comment by Hunsu** [comment]
You can't give the user a code like this CODE-a0bd677c-e9de-11e4-b02c-1681e6b88ec1. You give him something that he can remember. Second it's you who defined the domain class so if now I decide to generate uuid for code that means I have to change the constraints and change the tests as well. It's too much trouble for nothing really.

**Comment by romain-malet** [comment]
You don't need to change domain, just the way to get a number to concat with "CODE-". Uuid bad example, but a timestamp could work, security apart...
