### ISSUE TITLE
Using Searchable Plugin

### ISSUE THREAD

**Issue by Hunsu** [romain-malet/ToulouseMusee#4]
What do you think about using this plugin to take care of the search option?

**Comment by romain-malet** [comment]
With a link to the plugin is better

**Comment by Hunsu** [comment]
https://grails.org/wiki/searchable%20plugin%20-%20quick%20start

**Comment by romain-malet** [comment]
It's for the first user story I think...
Regarding to the requirement: a single query not very complicated, I don't think you will save time by using it.
If I have to implement this user story, I will not use the plugin.

**Comment by romain-malet** [comment]
Finally, you didn't use it ?
